# Generated by Django 4.0.5 on 2022-07-04 20:27

import app.cards.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=app.cards.storages.StorageAllowingDirectURLSave, upload_to=''),
        ),
    ]
