# Generated by Django 4.0.5 on 2022-07-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('access_level', models.CharField(choices=[('P', 'Public'), ('W', 'Workspace')], default='W', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BoardOpenTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Last Opened time')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
            ],
            options={
                'verbose_name': 'last_opened_board',
                'get_latest_by': 'time',
            },
        ),
    ]
